name = "icetype-docs"
account_id = "a826340b3b93189c9ebb7c0eaeba3c46"  # Semantics.dev
compatibility_date = "2025-01-01"

[assets]
directory = "./out"

[[routes]]
pattern = "docs.icetype.dev/*"
zone_name = "icetype.dev"
